[package]
name = "game_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = { version = "0.8.7", features = ["luajit", "macros", "vendored", "serialize"] }

tokio = { version = "1", features = ["rt"] }
tokio-stream = "0.1.11"

async-nats = "0.26.0"
serde = "1.0.152"
serde_json = "1.0.91"
walkdir = "2"
anyhow = "1.0.68"

tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[dev-dependencies]
criterion = "0.4.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3